FROM nginx:1.15

WORKDIR /app

# COPY ./build .
COPY ./build/ /usr/share/nginx/html
# Copy the default nginx.conf provided by tiangolo/node-frontend
COPY ./docker/nginx.conf /etc/nginx/conf.d/default.conf

EXPOSE 3000

# [BUILD IMAGE]:
# docker build -t weuse-production -f ./docker/Dockerfile.production2 .

# [RUN IMAGE]:
# docker run -p 80:80 weuse-production
#               ^^:^^
#  machine's host : container's host